// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umtvloreqixqximzxwcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtdHZsb3JlcWl4cXhpbXp4d2NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4OTA0MjgsImV4cCI6MjA1NTQ2NjQyOH0.gKuKPfO8MS-hZVf73Nv5icgfa464WNaO9cGTb05BLJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);